### ISSUE TITLE
Changelog widget does not appear when soft hide is turned off

### ISSUE THREAD

**Issue by quinnleong** [headwayappco/widget#36]
Hi there,

I have a question about getting the widget to display with the soft-hide badge setting disabled. With it enabled, the widget appears as expected. However, with it off, clicking does not show the widget at all. Here's a gif showing the that:

![headway-issue](https://user-images.githubusercontent.com/17228094/118197358-a0c37e00-b403-11eb-9285-3afce105648d.gif)

I'm wondering if this is expected behavior? I.e. if the badge is not shown, is it assumed that clicking the element the badge would otherwise be anchored to should not allow the widget to appear?

Thank you!

**Comment by majkelcc** [comment]
Hello @quinnleong 👋

Nice to hear from you, we're delighted having Honeycomb onboard <3

The attached gif made it easy to figure out what is going on, thanks! The good news is that `soft-hide` is working as you expected it to and after checking your app, the fix looks easy.

## What is happening

You have a custom icon inside a link to your full changelog page. That's also the element pointed by the `selector` for our badge to appear. With custom CSS your app stretched the container of our widget to cover the whole icon so that when it's clicked it's actually our badge (`HW_badge_cont`) that's getting clicked - and opens the widget.

When you disable `soft-hide` feature, the badge is not added to the DOM and clicking on your icon is not opening the widget anymore.

## How to fix

If you add `trigger: "#changelog"` option to your config, the whole link will act like an external, independent from our badge trigger, and will work even when the badge is not there.

```js
  var HW_config = {
    selector: "#changelog",
    trigger: "#changelog",
    ...
  }
```

Let me know if it helps!

Soon we'll be working on updated documentation for our widget and we'll make sure to cover common use cases like this one ✌️🙂

**Comment by quinnleong** [comment]
Thank you so much @majkelcc, for the quick response and this easy fix! That worked perfectly! 🎉
